### ISSUE TITLE
HOOBS certification

### ISSUE THREAD

**Issue by BobbySlope** [honkmaster/homebridge-mi-flower-care#31]
hi @honkmaster we like to certify your plugin for HOOBS
please contact us via plugindev@hoobs.org and send us your email dress to invite you to our Slack

Regards Bobby

**Comment by honkmaster** [comment]
Please send me more details why I would want to certify the component and what the implications are (legally, ...). You may find a contact form or my Mail address on my personal website.

**Comment by MiranoVerhoef** [comment]
Please add support for hoobs, Alot of people use this since its provides a much nicer out of the box experience. It makes configuration and finding of your pluging alot easier. Please contact hoobs about this. I just ran into issues when trying to install your plugin, since the depedencies are not installed, which is hard to install on hoobs

**Comment by honkmaster** [comment]
This may sound harsh: HOOBS want this plugin on their platform. Thus, they are in charge.
I asked for a mail with details, because they are missing on their website. 
This mail I have never received. Therefore, I am currently not willing to invest any more time. Sorry.

**Comment by BobbySlope** [comment]
@honkmaster please send me an email again to bobby@hoobs.org
i missed the comment above one you mentioned.
we really like to get this plugin working on HOOBS

**Comment by honkmaster** [comment]
Close as I never received a mail from HOOBS. The developer should not have to take action if someone else wants to get a benefit for their own platform.
